# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-17 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=400)),
                ('short_url', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=400)),
                ('status_codes', models.CharField(max_length=400)),
            ],
        ),
    ]
