# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-17 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='status',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='urls',
            name='status_codes',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
